### ISSUE TITLE
Can't connect to server or invalid credentials

### ISSUE THREAD

**Issue by jamespo** [glasswalk3r/spamcup-ng#1]
I presume due to a spamcop.net redesign this script (& the original) now give

E: Can't connect to server or invalid credentials. Please verify your username and password and try again.

**Comment by glasswalk3r** [comment]
Nope, I justed used spamcup-ng and it is working fine. Also, the interface remains the same.
I suggest to you to git clone this repository (I updated many thing, but nothing related to this issue), generate a new tarball with Dist::Zilla and install it.
After configuring properly, don't forget to enable DEBUG from it. You should see more information that would help identifying the issue.
In my experience, you account on Spamcop might have some issues (that unfortunately I don't think there is a test case on spamcup-ng to identify it), so log into spamcop.net manually and check what is happening over there.

**Comment by glasswalk3r** [comment]
Since got nothing from jamespo after almost a year, I'm closing this one.
